In [1]:
import numpy as np

In [2]:
camera = np.array([
    [0, -1, 0, 4],
    [1, 0, 1, -4],
    [-1, -0, 1, -15],
    [0, 0, 0,1]
])
print(camera)
np.linalg.inv(camera)

[[  0  -1   0   4]
 [  1   0   1  -4]
 [ -1   0   1 -15]
 [  0   0   0   1]]


array([[ 0. ,  0.5, -0.5, -5.5],
       [-1. ,  0. ,  0. ,  4. ],
       [ 0. ,  0.5,  0.5,  9.5],
       [ 0. ,  0. ,  0. ,  1. ]])

In [3]:
n1 = np.array([1, 2, 3, 4])
n2 = np.array([5, 6, 7, 8])
n3 = np.array([9, 10, 11, 12])
n4 = np.array([13, 14, 15, 16])
mat = np.array([n1, n2, n3, n4])
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [4]:
1 * 0 + 2 * 1 + 3 * -1 + 4 * 0

-1

In [5]:
1 * -1 + 2 * 0 + 3 * 0 + 4 * 0

-1

In [6]:
1 * 0 + 2 * 1 + 3 * 1 + 4 * 0

5

In [7]:
np.matmul(mat, camera)

array([[  -1,   -1,    5,  -45],
       [  -1,   -5,   13, -101],
       [  -1,   -9,   21, -157],
       [  -1,  -13,   29, -213]])

In [8]:
np.matmul(camera, mat)

array([[  47,   50,   53,   56],
       [ -42,  -44,  -46,  -48],
       [-187, -202, -217, -232],
       [  13,   14,   15,   16]])

In [12]:
np.matmul(mat, np.array([1, 2, 3, 4]))

array([ 30,  70, 110, 150])