# Matrix

In [9]:
import math
import numpy as np

In [10]:
m1 = np.array([
    [4, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 2, 0],
    [0, 0, 0, 1]
])
m2 = np.array([
    [1, 0, 0, 1],
    [0, 1, 0, 2],
    [0, 0, 1, 3],
    [0, 0, 0, 1]
])
np.matmul(m1, m2)

array([[4, 0, 0, 4],
       [0, 1, 0, 2],
       [0, 0, 2, 6],
       [0, 0, 0, 1]])

In [11]:
m3 = np.array([
    [0, 1, 0, 0],
    [1, 0, 0, 0],
    [0, 0, 1, 0],
    [0, 0, 0, 1]
])
np.matmul(m3, np.matmul(m1, m2))

array([[0, 1, 0, 2],
       [4, 0, 0, 4],
       [0, 0, 2, 6],
       [0, 0, 0, 1]])

In [17]:
v = np.array([3, 2, 1, 1])
np.matmul(m2, v)

array([4, 4, 4, 1])

In [12]:
MVP = np.array([
    [-1.8, 0, -1.5, 0],
    [0, -2.37, -1.5, -0.03],
    [0, 0.44, 15, -0.2],
    [0, 0, -1, 0]
])
np.linalg.inv(MVP)

array([[-5.55555556e-01,  0.00000000e+00, -6.28458147e-18,
         8.33333333e-01],
       [ 0.00000000e+00, -4.10509031e-01,  6.15763547e-02,
         1.53940887e+00],
       [ 0.00000000e+00,  0.00000000e+00,  7.54149776e-18,
        -1.00000000e+00],
       [ 0.00000000e+00, -9.03119869e-01, -4.86453202e+00,
        -7.16133005e+01]])

In [14]:
tmp = np.matmul(np.linalg.inv(MVP), np.array([0, 0, 0.98, 1]))
print(tmp)
tmp / tmp[3]

[  0.83333333   1.59975369  -1.         -76.38054187]


array([-0.01091028, -0.02094452,  0.01309234,  1.        ])